library(lme4)
library(ggplot2)
library(coefplot2)

## All complexity

setwd("/Users/Dani/UCD/BILs/leaf_traits/") ## Change to the directory to which you saved the data files
# load data tables
comp <- read.delim("BIL.complexity.all.2011.txt")
head(comp)  
summary(comp)
nlevels(comp$genotype) # 545
comp$block <- as.factor(substr(comp$plant,1,1)) # capture block information from the plant ID
head(comp$genotype)
levels(comp$genotype) # ** zeroes need to be added to the BIL#s for BILs less than 100
comp.rn <- comp
comp.rn$genotype <- as.character(comp.rn$genotype)
# ADD zeroes to too short BIL IDs
len6idx <- which(nchar(comp.rn$genotype[]) == 6) # length == 6 BIL names indices
len5idx <- which(nchar(comp.rn$genotype[]) == 5) # length == 5 BIL names indices
comp.rn$genotype[len6idx] <- paste0("BIL_0", substr(comp.rn$genotype[len6idx], 5, 6))
comp.rn$genotype[len5idx] <- paste0("BIL_00", substr(comp.rn$genotype[len5idx], 5, 5))
comp.rn$genotype
as.factor(comp.rn$genotype)

load("~/UCD/BILs/bil.reassign.Rdata") ##** Load bil.reassign, which is generated by bin_classif.R script.
comp.rn <- merge(comp.rn, bil.reassign, by.x="genotype", by.y="BIL") # merge by original BIL# assignment
head(comp.rn, 50)
comp.rn$genotype <- as.factor(comp.rn$genotype)
comp.rn$FinBIL <- as.factor(comp.rn$FinBIL)
levels(comp.rn$FinBIL)
comp.rn$FinBIL<- relevel(comp.rn$FinBIL, "M82")
#
all.x <- lmer(all ~ FinBIL + (1|block) + (1|plant), comp.rn, REML=T)
all.x  
fixef(all.x)

class(coeftab(all.x))
ct <- as.data.frame(coeftab(all.x))
summary(ct)
head(ct)
rownames(ct)[1] <- "M82"
head(ct)
ct$geno <- rownames(ct)
ct$geno[2:nrow(ct)] <- substr(ct$geno[2:nrow(ct)],7,13)
ct$geno
head(ct)
# convert from coefficient table to "prediction" table

ct[2:nrow(ct),1] <- ct[2:nrow(ct),1] + ct[1,1] # i.e. add the intercept estimate to the genotype coefficients' estimates 
ct[2:nrow(ct),3:6] <- ct[2:nrow(ct),3:6] + ct[1,1] # ...and also add the intercept to the quantile estimates of the genotype coefficients
head(ct)
ct$estPse <- ct$Estimate + ct[,2] # estimate + std err -- calculate upper error bar limit
ct$estMse<- ct$Estimate - ct[,2] # estimate - std err -- calculate lower error bar limit
head(ct)
#ct[,1:6] <- as.numeric(ct[,1:6])
class(ct$estPse)
class(ct)
names(ct)[2] <- 'Std._Error'
summary(ct)
ct <- ct[with(ct, order(Estimate)), ]
head(ct)
ctp <- ct
ctp$geno <- factor(ctp$geno, levels=ctp$geno)
# Plot the whole distribution of predicted genotype effects on "all" complexity counts
ggplot(ctp, aes(y=Estimate, x=geno, ymin=Estimate - Std._Error, ymax=Estimate + Std._Error)) + geom_pointrange() + theme_bw() +
  theme(axis.text.x = element_text(size=3.5, angle=50, vjust=1, hjust=1))

head(ct)
head(comp.rn)
summary(comp.rn)
ctall <- ct
ctall$type <- 'all'
head(ctall)
#save(ctall, file="/Users/Dani/UCD/BILs/leaf_traits/ctall.Rdata")
```

## Primary complexity

mpri <- lmer(pri ~ FinBIL + (1|block) + (1|plant), comp.rn, REML=F)
ctpri <- as.data.frame(coeftab(mpri))

summary(ctpri)
head(ctpri)
rownames(ctpri)[1] <- "M82"
head(ctpri)
ctpri$geno <- rownames(ctpri)
ctpri$geno[2:nrow(ctpri)] <- substr(ctpri$geno[2:nrow(ctpri)],7,13)
ctpri$geno
head(ctpri)
# convert from coefficient table to "prediction" table

ctpri[2:nrow(ctpri),1] <- ctpri[2:nrow(ctpri),1] + ctpri[1,1]
ctpri[2:nrow(ctpri),3:6] <- ctpri[2:nrow(ctpri),3:6] + ctpri[1,1]
head(ctpri)
ctpri$estPse <- ctpri$Estimate + ctpri[,2] # estimate + std err
ctpri$estMse<- ctpri$Estimate - ctpri[,2] # estimate - std err 
head(ctpri)
#ctpri[,1:6] <- as.numeric(ctpri[,1:6])
class(ctpri$estPse)
class(ctpri)
names(ctpri)[2] <- 'Std._Error'
summary(ctpri)
ctpri <- ctpri[with(ctpri, order(Estimate)), ]
head(ctpri)
ctpri$type <- 'primary'

ctp <- ctpri
ctp$geno <- factor(ctp$geno, levels=ctp$geno)
# Plot the whole distribution of predicted genotype effects on "all" complexity counts
ggplot(ctp, aes(y=Estimate, x=geno, ymin=Estimate - Std._Error, ymax=Estimate + Std._Error)) + geom_pointrange() + theme_bw() +
  theme(axis.text.x = element_text(size=3.5, angle=50, vjust=1, hjust=1))


## Intercallary complexity

mint <- lmer(int ~ FinBIL + (1|block) (1|plant), comp.rn, REML=F)
ctint <- as.data.frame(coeftab(mint))

summary(ctint)
head(ctint)
rownames(ctint)[1] <- "M82"
head(ctint)
ctint$geno <- rownames(ctint)
ctint$geno[2:nrow(ctint)] <- substr(ctint$geno[2:nrow(ctint)],7,13)
ctint$geno
head(ctint)
# convert from coefficient table to "prediction" table

ctint[2:nrow(ctint),1] <- ctint[2:nrow(ctint),1] + ctint[1,1]
ctint[2:nrow(ctint),3:6] <- ctint[2:nrow(ctint),3:6] + ctint[1,1]
head(ctint)
ctint$estPse <- ctint$Estimate + ctint[,2] # estimate + std err
ctint$estMse<- ctint$Estimate - ctint[,2] # estimate - std err 
head(ctint)
#ctint[,1:6] <- as.numeric(ctint[,1:6])
class(ctint$estPse)
class(ctint)
names(ctint)[2] <- 'Std._Error'
summary(ctint)
ctint <- ctint[with(ctint, order(Estimate)), ]
head(ctint)
ctint$type <- 'intercallary'

ctp <- ctint
ctp$geno <- factor(ctp$geno, levels=ctp$geno)
# Plot the whole distribution of predicted genotype effects on "all" complexity counts
ggplot(ctp, aes(y=Estimate, x=geno, ymin=Estimate - Std._Error, ymax=Estimate + Std._Error)) + geom_pointrange() + theme_bw() +
  theme(axis.text.x = element_text(size=3.5, angle=50, vjust=1, hjust=1))


## Secondary complexity


msec <- lmer(sec ~ FinBIL + (1|block) + (1|plant), comp.rn, REML=F)
ctsec <- as.data.frame(coeftab(msec))

summary(ctsec)
head(ctsec)
rownames(ctsec)[1] <- "M82"
head(ctsec)
ctsec$geno <- rownames(ctsec)
ctsec$geno[2:nrow(ctsec)] <- substr(ctsec$geno[2:nrow(ctsec)],7,13)
ctsec$geno
head(ctsec)
# convert from coefficient table to "prediction" table

ctsec[2:nrow(ctsec),1] <- ctsec[2:nrow(ctsec),1] + ctsec[1,1]
ctsec[2:nrow(ctsec),3:6] <- ctsec[2:nrow(ctsec),3:6] + ctsec[1,1]
head(ctsec)
ctsec$estPse <- ctsec$Estimate + ctsec[,2] # estimate + std err
ctsec$estMse<- ctsec$Estimate - ctsec[,2] # estimate - std err 
head(ctsec)
#ctsec[,1:6] <- as.numeric(ctsec[,1:6])
class(ctsec$estPse)
class(ctsec)
names(ctsec)[2] <- 'Std._Error'
summary(ctsec)
ctsec <- ctsec[with(ctsec, order(Estimate)), ]
head(ctsec)
ctsec$type <- 'secondary'
dim(ctsec)

ctp <- ctsec
ctp$geno <- factor(ctp$geno, levels=ctp$geno)
# Plot the whole distribution of predicted genotype effects on "all" complexity counts
ggplot(ctp, aes(y=Estimate, x=geno, ymin=Estimate - Std._Error, ymax=Estimate + Std._Error)) + geom_pointrange() + theme_bw() +
  theme(axis.text.x = element_text(size=3.5, angle=50, vjust=1, hjust=1))



## NOTE: in this code chunk I'm joining together the parts of the data that will make up the data matrix for clustering
## 
library(plyr)
library(reshape2)
cEst <- join_all(list(ctpri[,c(1,7,10)], ctint[,c(1,7,10)], ctsec[,c(1,7,10)], ctall[,c(1,7,10)]), by=c('geno','type') , type='full')
cEst 
#summary(cEst)
cEst$geno <- as.factor(cEst$geno)
cEst$type <- as.factor(cEst$type)
summary(cEst)
rownames(cEst) <- paste0(cEst$geno,"_",cEst$type)
head(cEst)
tail(cEst)
dim(cEst)
cEst$ID <- rownames(cEst)



ce.noM82 <- cEst[cEst$geno!="M82",]
dim(ce.noM82)
head(ce.noM82)
ceo <- arrange(ce.noM82, geno, type)
head(ceo)
unique(ceo$geno)

cldat <- data.frame(primary=ceo[ceo$type=="primary",1], intercallary=ceo[ceo$type=="intercallary",1], secondary=ceo[ceo$type=="secondary",1], all=ceo[ceo$type=="all",1])
head(cldat)
rownames(cldat) <- unique(ceo$geno)
head(cldat)


## For SparseNet mapping I should use the predicted values ignoring random effects